version: '3'

services:
  postgres:
    image: postgres:14.1
    container_name: database
    restart: always
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: ${POSTGRES_DB:-go-product-showcase}
      TZ: 'GMT-3'
      PGTZ: 'GMT-3'

    ports:
      - 5432:5432

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "db_prod" ]
      timeout: 30s
      interval: 10s
      retries: 5
      start_period: 5s

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: broker
    restart: always
    ports:
      - 5672:5672
      - 15672:15672

    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:15672" ]
      interval: 30s
      timeout: 10s
      start_period: 5s
      retries: 5

  jaeger:
    image: jaegertracing/all-in-one:1.32
    container_name: otel
    restart: always
    environment:
      COLLECTOR_ZIPKIN_HOST_PORT: 9411

    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14250:14250
      - 14268:14268
      - 14269:14269
      - 9411:9411
