name: check change log

on: 
  release:
    types:
      - published

jobs:
  remind:
    name: Changelog Reminder
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Changelog Reminder
        uses: peterjgrainger/action-changelog-reminder@v1.2.0
        with:
          changelog_regex: "CHANGELOG.md"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
